### ISSUE TITLE
python tools/generate_acronym_dataset.py

### ISSUE THREAD

**Issue by huaji98** [NVlabs/SceneCollisionNet#1]
**specified material (m0)  not loaded!
concatenating texture: may result in visual artifacts**
Processing Meshes:  94%|████████████████▊ | 8280/8836 [1:15:30<06:21,  1.46it/s]specified material (m1)  not loaded!
specified material (m2)  not loaded!
specified material (m0)  not loaded!
specified material (m0)  not loaded!
specified material (m2)  not loaded!
specified material (m1)  not loaded!
specified material (m0)  not loaded!

I have no idea for this warning.

**Comment by mjd3** [comment]
Hi @huaji98,

These warnings shouldn't affect performance as they are just related to the mesh materials not loading correctly. However, the geometry is still processed correctly and training should proceed fine.
